### ISSUE TITLE
[BUG] `play` throws an error when run without arguments, and it shouldn't.

### ISSUE THREAD

**Issue by Ike-Clinton** [ltackett/musictocodeto#5]
When issuing the command "play", a random playlist is loaded however an error is thrown.
"error: no track loaded."

Instead of throwing the error it would be a small quality of life change to just have it play the random list without saying an error is thrown.

**Comment by ltackett** [comment]
@Ike-Clinton — agreed completely.

Based on the metrics I've gotten from folks banging out commands today, I have a much more sensible command API coming soon.

**Comment by ltackett** [comment]
This is fixed with the new commands API. Closing.
