### ISSUE TITLE
[BUG] When `player skip` is run with no args, app hangs cosmetically

### ISSUE THREAD

**Issue by Ike-Clinton** [ltackett/musictocodeto#6]
Running "player skip" with no args throws the program into a loop that doesn't return properly.

**Comment by ltackett** [comment]
@Ike-Clinton — strictly speaking, this is only an infinite loop cosmetically. As a temporary work-around, you can `cmd+a` to select all, backspace, and hit enter again to send a blank command. This will fire off the event to signal the system that a command has stopped running.

Bloody annoying, and definitely at the top of my list for things I need to fix. Such is the joy if hacking stuff out over a weekend without any paper diagrams.

**Comment by ltackett** [comment]
new player commands API fixes this
